<?= $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<?= $this->render ("head.phtml") ?>
<?
 $user = Zend_Auth::getInstance()->getIdentity();
 echo "<!-- user: $user -->\n";
?>
<body>


<div id='header-wrap'><div id='header-content'>
<?= $this->render ("menu.phtml") ?>
</div></div>


<div id='content-wrap'><div id='content'>

<div id='main'>
<?= $this->layout()->content; ?>
</div> <!-- main -->

<div id='sidebar'>
<?= $this->render ("righthand.phtml"); ?>
</div>  <!-- sidebar -->
 </div> </div> <!-- content-wrap, content -->


<div id='footer-wrap'><div id='footer-content'>
<?= $this->render ("footer.phtml") ?>
</div></div> <!-- footer-content, footer-wrap -->
</body>
</html>

