<?
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl() ;

$user = $this->user; 

$thispage = $this->url(array("action" => "index") ) ;


echo $this->paginationControl ($this->paginator, 'Sliding', "pagination.phtml");
echo "<table class='styled' style='width:300px'>";
echo "<tr class='styled'><th class='styled' align='center'>ID</th><th class='styled' align='center'>Problem ID</th><th class='styled' align='center'>Submission<br /> Time</th>
<th class='styled' align='center'>User</th>
<th class='styled' align='center'> Language </th>

<th class='styled' align='center'>Score</th><th class='styled' align='center'>Status</th></tr>";

$mee = User::factory(Zend_Auth::getInstance()->getIdentity()); 
if ( empty($mee) ) $isadmin = false ; 
 else $isadmin = $mee -> isAdmin() ;

$rowcount=0;
$curtime = time ();
foreach ( $this->paginator as $x ) {
  //  print_r ($x);
  $access = (  Zend_Auth::getInstance()->getIdentity() == $x->uid) ;
  if ( $isadmin ) $access = true ;
  
  echo "<tr class='styled";
  if($rowcount%2==0){
      echo "a";
  }
  echo "'>";
  if ( ! $access ) 
	echo " <td> " . $x->id ." </td>";
  else 
	echo "<td> <a href='$baseurl/results/{$x->id}'> {$x->id} </a></td>";
  
  $abstime = strftime("%d %b %Y %H:%M:%S %z",strtotime($x -> time ));
  $ts = $this->timeDifference (strtotime ($x->time), $curtime); 
  //  echo "<td class='styled'>". print_r(strtotime($x -> time )) . "</td>" ;
  echo " <td class='styled' align='center'> <a href='$baseurl/problems/{$x->problemid}'>" . $x->problemid . "</a></td>\n ";
  echo "<td class='styled' align='center' title='$abstime'>$ts</td>\n";
  
  echo " <td class='styled' align='center'> <a href='$baseurl/users/{$x->uid}'>" . $this->shortenText ($x->username, 12) . "</a> </td>\n" ;
  if ( $x -> lang == "cpp" ) $flang = "C++" ;
  elseif ( $x->lang == "c" ) $flang = "C" ; 
  elseif ($x->lang == "gcj" ) $flang = "Java" ; 
  else $flang = $x->lang ;

  echo " <td class='styled' align='center'> $flang </td> \n" ;
  echo "<td class='styled' align='center'> " . $x -> score . " </td>\n" ;
  if ( !$access) {
  echo "<td class='styled' align='center'> " . $this->shortenText ($x ->state, 12) . "</td>\n" ;
  }
  else {
	echo "<td class='styled' align='center'><a href='$baseurl/results/{$x->id}'>" ;
	echo $this->shortenText ($x->state, 12) . "</a></td>";
  }
  
  echo "</tr>\n";
  $rowcount++;
}

echo "</table>";

echo $this->paginationControl ($this->paginator, 'Sliding', "pagination.phtml");
?>



