<table class='styled'>
  <tr class='styled'>
    <th class='styled'>#</th>
    <th class='styled'>ID</th>
    <th class='styled'>Name</th>
  </tr>

<?
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl() ; 
foreach ( $this->problems as $pro ) { 
  echo "  <tr><td>{$pro->rowid}</td><td><a href='$baseurl/problems/{$pro->id}'>{$pro->id}</a></td><td><a href='$baseurl/problems/{$pro->id}'>{$pro->nickname}</a></td></tr>\n";
}
?></table>
