<?
$isuser = Zend_Auth::getInstance()->hasIdentity();
?>
<table class='styled'>
  <tr class='styled'>
    <th class='styled' align='right'>#</th>
    <th class='styled'>ID</th>
    <th class='styled'>Name</th>
    <? if ($isuser) echo "<th class='styled'>State</th>"; ?>
  </tr>

<?
   $class = "styled";
$baseurl = webconfig::getContestRelativeBaseUrl (); 
foreach ( $this->problems as $pro ) { 
  echo "  <tr class='$class'>
	<td class='$class' align='right'>{$pro->rowid}</td>
	<td class='$class'>" . $this->link ("/problems/{$pro->id}", $pro->id) .
       "</td>
	<td class='$class'> " . $this->link ("/problems/{$pro->id}", $pro->nickname) . "</td>";
  if ($isuser) 
    echo "<td class='$class'>{$pro->state}</td>";
  echo "</tr>\n";
  if ($class == "styled") $class = "styleda";
  else $class = "styled";
}
?></table>
