<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="robots" content="index,follow" />
  <?
?><style type="text/css" media="screen" >
	@import url("<?= $this->buildUrl ('/public/styles/basic.css') ?>" ); 
  </style>
  <link rel="icon" href="<?= $this->buildUrl ('/public/images/' . webconfig::$logo) ?>" />
  <title><? if (!empty($this->title)) echo $this->escape($this->title) . " - "; echo webconfig::getContestName();  ?></title>
</head>
