<?

$base_url = Zend_Controller_Front::getInstance()->getBaseUrl() . webconfig::getContestRelativeBaseUrl(); 
/* strip off trailing / */
$base_url = substr ($base_url, 0, strlen($base_url)-1);

$static_baseurl = webconfig::$static_baseurl;
?>

<div id="header">

  <?= $this->link (webconfig::$logo_href, 
		   "<img alt='logo' src='" . $this->buildUrl ("/public/images/") . webconfig::$logo . "'/>",
	       array ("class" => "cmilogo"));?>

<?php
$main_menu =array();
$main_pages=array();

$_auth = Zend_Auth::getInstance() ; 


require_once "lib/contest.inc" ;
$contest = Contest::factory(webconfig::getContestId()) ;
$xp = $contest->getXPath() ;
$pages = $xp->query("/contest/frontend/page");

foreach ($pages as $page) { 
  $id = $xp->query('@id', $page)->item(0)->nodeValue;
  array_push($main_menu, $page->nodeValue);
  array_push($main_pages, "pages/$id");
}
if ( Zend_Auth::getInstance()->hasIdentity() ) { 
  array_push($main_menu,"Profile");
  array_push($main_pages,"profile/update");
 }

$i = 0;

echo '<div class="topmenu">' ; 
foreach ($main_menu As $option) {
    if($i==0){
        $ii=1;
    }else{
	  echo " <span style='font-size: smaller'>|</span> " ;
        $ii = ($i%4)+2;
    }
?><a  href='<? echo "$base_url/$main_pages[$i]"?>'   > 
		 <? echo $main_menu[$i] ?> 	   
	  </a> 
<?
    ++$i;
}

echo "</div> <!-- topmenu --> "; 
echo "</div> <!-- header --> ";
?>

<div id="headerbar">
<div id="sublinks">
<?php 
 
  $contest_menu=array();
$contest_pages=array();

/*
array_push($contest_menu, "Team List");
array_push($contest_pages, "info/?form=teamlist");
*/

  {
	array_push($contest_menu, "Problems");
	array_push($contest_pages, "problems/");
	
	array_push($contest_menu, "Submit");
	
	if ( empty($this->problem_code) ) 
	  array_push($contest_pages,"submit/");
	else
	  array_push($contest_pages,"submit/?probid={$this->problem_code}");
	
	array_push($contest_menu, "Rankings");
	array_push($contest_pages,"ranks/");
	
	array_push($contest_menu,"Queue Status");
	array_push($contest_pages,"queue");

	if ( Zend_Auth::getInstance()->hasIdentity()) { 
		array_push($contest_menu, "My Submissions");
		array_push($contest_pages, "queue/mine");
	}
	
  }


$i = 0;
foreach ($contest_menu as $option) {
  echo $this->link ("/$contest_pages[$i]", $option);
  ++$i;
}

if ( Zend_Auth::getInstance()->hasIdentity() ) 
  echo $this->link ("/auth/logout", "Logout");

echo "</div> <!-- sublinks --> \n</div> <!--subheader-->\n ";
//$option = $contest_menu[$i]; //Why do we need this?


if ( !empty($this->login_message) )  
  {
	
	echo ' 
<script type="text/javascript">
document.getElementById("wronglogin").innerHTML = "Incorrect Login";
</script>';
	
  }







