<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<table class="paginationControl">
<tr> <td>
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    &lt;&lt;
  </a>
<?php else: ?>
  <span class="disabled">&lt;&lt;</span>
</td>
<?php endif; ?>


<td>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Newer
  </a> 
<?php else: ?>
  <span class="disabled">&lt; Previous</span> 
<?php endif; ?>
</td>


<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <td>
  <?php if ($page != $this->current): ?>

    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a>
  <?php else: ?>
    <?php echo $page; ?>
  <?php endif; ?>
  </td>
<?php endforeach; ?>

<td>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Older &gt;
  </a>
<?php else: ?>
  <span class="disabled">Older &gt;</span>
<?php endif; ?>
</td>

<td>
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    &gt;&gt;
  </a>
<?php else: ?>
  <span class="disabled">&gt;&gt;</span>
<?php endif; ?>
</td>

</tr>
</table>
<?php endif; ?>


