<?
   $base_url = Zend_Controller_Front::getInstance()->getBaseUrl() ; 


   if ( ! Zend_Auth::getInstance()->hasIdentity() )  { 
	echo "<h1>Login</h1>";
	echo "<form method='post' action='$base_url/auth/login' >
      <div>
        <input type='hidden' name='redirectto' value='" . (empty($this->login_redirect) ? Zend_Controller_Front::getInstance()->getRequest()->getPathInfo() : $this->login_redirect) . "'/>
        <label for='username' >Username</label>
        <input id='username' type='text' name='username' />

        <label for='password'>Password</label>
        <input id='password' type='password' name='password' />
        <input type='submit' id='submit' value='Login' />";
	 if (webconfig::$allow_register) 
	   echo "<a id='registerlink' href='$base_url/profile/register/' >Register Now</a><span id='wronglogin'></span>";
	 echo "</div></form>
";
	   }
   else { 
	echo "<h1> Hello " . User::factory(Zend_Auth::getInstance()->getIdentity())->getUsername () . "!</h1>
    <ul class='sidemenu'> 
      <li><a href=\"{$this->url(array('action'=>'update', 'controller'=>'profile'))}\">Update Profile</a></li>
      <li><a href=\"{$this->url(array('action'=>'logout', 'controller'=>'auth'))}\">Logout</a></li>
    </ul>";

	   echo "<p>Current Server Time: <br /> ". 
	   date(DATE_RFC1123) . "</p>"; 
	 echo "<p>";
	Zend_Loader::loadClass("ContestModel");
	$contestm = new ContestModel() ;
	$state = $contestm->getContestState(webconfig::getContestId()); 
	$contest = $contestm->getRow(webconfig::getContestId());
	
	 if (strtotime("+1 Year") < $contest->getContestEndTime()) {
	   echo "<!-- contest does not end anytime soon -->\n";
	 } 
	 elseif ( $state == "before" ) {
	   echo webconfig::getContestName() . " starts at: <br/>" . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestTime()) ;
	 }
	 elseif ($state == "ongoing") {
	   echo webconfig::getContestName() . " ends at: <br/>" . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestEndTime()) ; 
	 }
	 elseif ($state == "after" ) {
	   echo webconfig::getContestName() . " has ended.<br />";
	   echo "<!-- End time : " . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestEndTime()) . " -->\n";

	 }
   
	 echo "</p>";


   }

echo "\n" ;

/* lets load any widgets */
foreach (webconfig::$widgets as $widget) { 
  echo $this->render($widget) ;
}
