<?
   $base_url = Zend_Controller_Front::getInstance()->getBaseUrl() ; 

echo "   <table id='announces'><tr><td>" ;

   if ( ! Zend_Auth::getInstance()->hasIdentity() )  { 
	echo "<form method='post' action='$base_url/auth/login' >
      <div>
        <input type='hidden' name='redirectto' value='" . (empty($this->login_redirect) ? Zend_Controller_Front::getInstance()->getRequest()->getPathInfo() : $this->login_redirect) . "'/>
        <label for='username' >Username</label>
        <input id='username' type='text' name='username' />

        <label for='password'>Password</label>
        <input id='password' type='password' name='password' />
        <input type='submit' id='submit' value='Login' />";
	 if (webconfig::$allow_register) 
	   echo "<a id='registerlink' href='$base_url/profile/register/' >Register Now</a><span id='wronglogin'></span>";
	 echo "</div></form>
";
	   }
   else { 

	   echo "<p style='font-size:smaller;'>Current Server Time: <br /> ". 
	   date(DATE_RFC1123) . "</p>"; 
	 echo "<p style='font-size:smaller;'>";
	Zend_Loader::loadClass("ContestModel");
	$contestm = new ContestModel() ;
	$state = $contestm->getContestState(webconfig::$contest_id); 
	$contest = $contestm->getRow(webconfig::$contest_id);
	
	 if (strtotime("+1 Year") < $contest->getContestEndTime()) {
	   echo "<!-- contest does not end anytime soon -->\n";
	 } 
	 elseif ( $state == "before" ) {
	   echo webconfig::$contest_name . " starts at: <br/>" . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestTime()) ;
	 }
	 elseif ($state == "ongoing") {
	   echo webconfig::$contest_name . " ends at: <br/>" . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestEndTime()) ; 
	 }
	 elseif ($state == "after" ) {
	   echo webconfig::$contest_name . " has ended.<br />";
	   echo "<!-- End time : " . strftime("%a, %d %b %Y %H:%M:%S %z", $contest->getContestEndTime()) . " -->\n";

	 }
   
	 echo "</p>";


   }

echo "    </td></tr>\n" ;

/* lets load any widgets */
foreach (webconfig::$widgets as $widget) { 
  echo "<tr><td>\n";
  echo $this->render($widget) ;
  echo "</td></tr>\n";
}
echo "  </table> <!-- announces -->\n";
